apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-service
  labels:
    app: auction-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auction-service
  template:
    metadata:
      labels:
        app: auction-service
    spec:
      containers:
        - name: auction-service
          image: auction-service-auction:latest # 실제 이미지 주소로 변경 필요
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod" # 또는 "k8s"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://server-discovery.default.svc.cluster.local:8761/eureka/"
            - name: CONFIG_SERVER_URL
              value: "http://server-config.default.svc.cluster.local:8888"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
