apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-gateway
  labels:
    app: server-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server-gateway
  template:
    metadata:
      labels:
        app: server-gateway
    spec:
      containers:
        - name: server-gateway
          image: chpark1993/auction-server-gateway:0.0.1
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://server-discovery.default.svc.cluster.local:8761/eureka/"
            - name: CONFIG_SERVER_URL
              value: "http://server-config.default.svc.cluster.local:8888"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
