apiVersion: v1
kind: Service
metadata:
  name: server-gateway
spec:
  selector:
    app: server-gateway
  ports:
    - protocol: TCP
      port: 80 # 외부에서 80 포트로 접근
      targetPort: 8080 # 컨테이너의 8080 포트로 트래픽 전달
  type: LoadBalancer # 외부 로드밸런서를 통해 서비스에 접근할 수 있도록 설정
